---
- name: get ec2 facts
  ec2_facts:

- debug: msg="{{ansible_ec2_public_ipv4}}"

- name: Install docker
  yum: name={{item}} state=present
  with_items:
    - docker
#TODO сделать lininfile, удобно если нод будет больше чем дефолтных 2
- name: Replace ip in nginx.conf
  replace:
    path: /etc/nginx/nginx.conf
    regexp: "{{app_name}}"
    replace: "{{ansible_ec2_public_ipv4}}"
  delegate_to: "{{item}}"
  with_items: "{{groups['ec2balancer']}}"

- name: Docker service is up
  service: name=docker state=started

- pip:
    name: docker-py
    extra_args: --user
  become: false

# TODO разобраться с docker-py и этим permission denied/pip:command not found(видимо где то проблема с PATH)
#- name: Start Docker
#  docker_container:
#    state: started
#    image: registry.gitlab.com/bablzz/devops-test-task
#    pull: true
#    name: devops-test-task
#    published_ports:
#      - "9007:9007"
#    restart_policy: unless-stopped
- name: Starting docker
  shell: >
    sudo docker pull registry.gitlab.com/bablzz/devops-test-task && \
    sudo docker run -d -p 9007:9007 registry.gitlab.com/bablzz/devops-test-task

- name: Set up prometheus
  template: src=templates/prometheus.yml.j2 dest=/tmp/prometheus.yml force=yes
  delegate_to: "{{item}}"
  with_items: "{{groups['ec2monitoring']}}"

- name: Starting node Exporter
  shell: >
    sudo docker run -d -p 9100:9100 -v "/proc:/host/proc" -v "/sys:/host/sys" -v "/:/rootfs" --net="host" prom/node-exporter -collector.procfs /host/proc -collector.sysfs /host/proc -collector.filesystem.ignored-mount-points "^/(sys|proc|dev|host|etc)($|/)"
